name: Violent
version: 1.0
author: nonkungch
main: me.manus.murdergame.MurderGame
api-version: 1.21
commands:
  volg:
    description: Main command for Violent
    usage: /volg [help|create|join|start|setlobby|setspawn|setexit|setsize|reload]
permissions:
  violent.admin:
    description: Admin permission for Violent plugin
    default: op
